### ISSUE TITLE
Drop old minecraft version support

### ISSUE THREAD

**Issue by bryceharrington** [benediktschmitt/emsm#100]
The current codebase provides support for vanilla minecraft 1.2 forward, forge 1.6 forward, and spigot 1.8 forward.  Some of the minecraft versions here are quite ancient and are probably not that interesting for emsm users.

The main problem I've seen with having so many supported versions is that it makes `minecraft -S server --update` take a lengthy time to complete.

A secondary problem is that external links will tend to bitrot over time, and fixing the urls will be an ongoing maintenance task for the Emsm project generally.  Given the limited number of contributors and maintainers, efforts may be better focused on the newer minecraft versions that are actually in use.

Third, and kind of related to the prior point, it's entirely possible for minecraft .jars to have security vulnerabilities, so providing old versions that aren't being updated actively enough, could expose Emsm's users to security issues for the old servers.

Finally, it's worth pointing out that Emsm does not retain old point versions.  I.e. when minecraft 1.12.2 came out, 1.12.1 was dropped.  So the project does already have a convention to drop support for old stuff, this would just be generalizing that.

For these reasons I'd propose dropping a lot of the old versions.  I know certain old versions are used as the basis of various mods and such (minecraft 1.7 is used as a base for some popular Forge mods, for example), so we may want to pick and choose a bit.  However, I think we could drop at least:

vanilla 1.2
vanilla 1.3
vanilla 1.4
vanilla 1.5
vanilla 1.6
vanilla 1.8
vanilla 1.9
minecraft forge 1.6
minecraft forge 1.8

I don't know anything about spigot but perhaps spigot 1.8 and/or 1.9 could also be dropped.

Is anyone still using any of these?  If not, any opposing thoughts to dropping them?

**Comment by AdorablePotato** [comment]
I still have old worlds which I'm coming back to from time to time. The reason for keeping only the latest version of each minor patch note is that they are downwards compatible. If `minecraft -S server --update` takes too long for you, then why not simply change the semantics of `-S` or better introduce a new  flag `-uS` (used servers or something along this line) to only select the server versions with active worlds?

The maintenance of the links has not been a problem until now. Mojang seems to keep them pretty stable as their client uses them as well. Also, the EMSM docs describe how users can change the URL via the configuration file in the case it breaks.

So I'd pretty much consider this a none-issue at this point.

Please tell me, if you're interest in the `-uS` flag (suggestions welcome)?

**Comment by bryceharrington** [comment]
minecraft forge 1.6:
	 reinstalling the server ...
minecraft forge 1.7:
	 reinstalling the server ...
minecraft forge 1.8:
	 reinstalling the server ...
	 error: The installation of the server 'minecraft forge 1.8' failed. The installation of the server 'minecraft forge 1.8' failed. Installer returned with '1'.
minecraft forge 1.10:
	 reinstalling the server ...
	 error: The installation of the server 'minecraft forge 1.10' failed. The installation of the server 'minecraft forge 1.10' failed. Installer returned with '1'.
minecraft forge 1.11:
	 reinstalling the server ...
	 error: The installation of the server 'minecraft forge 1.11' failed. The installation of the server 'minecraft forge 1.11' failed. Installer returned with '1'.
