### ISSUE TITLE
FileLock not importing

### ISSUE THREAD

**Issue by sixstringsg** [benediktschmitt/emsm#44]
FileLock is installed, and other python scripts can use it, but emsm won't import it properly. 
```
jstew@haf ~ $ minecraft
Traceback (most recent call last):
  File "/usr/bin/minecraft", line 34, in <module>
    import emsm
  File "/opt/minecraft/emsm/__init__.py", line 35, in <module>
    from . import application
  File "/opt/minecraft/emsm/application.py", line 38, in <module>
    import filelock
ImportError: No module named 'filelock'
```

**Comment by benediktschmitt** [comment]
Did you install the ``filelock`` module from pypi (``pip install filelock``)?

You can find all required packages from pypi in the ``emsm/requirements.txt`` file.

**Comment by VonOx** [comment]
@sixstringsg 

run this to be sure filelock for python3 is installed
`python3 -m pip install filelock`

**Comment by benediktschmitt** [comment]
@sixstringsg thanks, I overlooked that.

Since the EMSM is now available at PyPi and the depencies are installed automatically, I think I can close this issue. If not, please reopen it.

**Comment by rushi-the-neural-arch** [comment]
`pip install --user filelock
`
For anyone facing this issue serverside

**Comment by SilkAndSlug** [comment]
Thanks
