### ISSUE TITLE
Use dpkg and rpm (or pip)

### ISSUE THREAD

**Issue by benediktschmitt** [benediktschmitt/emsm#46]
In the long term, the EMSM should be installed and updated using the debian package manager and the red hat package manager. A lot of things would become simpler.

**Comment by lukesneeringer** [comment]
To play devil's advocate, rpm and yum are probably more than you really need. Just being able to install emsm under pip would be almost as good, and _much_ easier.

Also, updating would be a far simpler task.

**Comment by benediktschmitt** [comment]
Sure, why not. The only file which is outside the EMSM folder is the link in */usr/bin/* and the *initd* script. But the link is never updated and the initd script rarely. So *pip* seems ok for me.

The *minecraft.py* file could be placed in the EMSM installation directory */opt/minecraft/* and import the EMSM.

**Comment by benediktschmitt** [comment]
Thanks for playing devil's advocate @lukesneeringer  :)

The EMSM can now be used as Python package and is available on [PyPi](https://pypi.python.org/pypi/emsm/). I will merge the pip-install branch, when I had time to test it.

The upgrade guide can be found in the [changelog](http://emsm.readthedocs.org/en/pip-install/changelog.html).
