### ISSUE TITLE
{server_path} in start_command doesn't work for forge servers

### ISSUE THREAD

**Issue by cuchaz** [benediktschmitt/emsm#49]
adding a
```
start_command = java -jar {server_path} nogui.
```
to a forge section in server.conf breaks the --start command

I glanced at your source... it looks like the cause might be because self._server for forge subclasses isn't set properly.
https://github.com/benediktschmitt/emsm/blob/master/emsm/server.py#L194

It looks like forge subclasses do some magic in default_start_cmd to get the path to the forge jar file.
https://github.com/benediktschmitt/emsm/blob/master/emsm/server.py#L706
but the normal start_cmd doesn't get access to that info.

**Comment by cuchaz** [comment]
emsm is pretty awesome, btw. =)

**Comment by benediktschmitt** [comment]
Thank you :)

You're right. The ``self._server`` variable is not used right. I simply wanted the server executable to be installed at this path, whether it is a whole directory or just a single file.

**Comment by benediktschmitt** [comment]
If you need a fast fix, you can explicitly specify the forge executable in the directory:

```
start_command = java -jar {server_path}/forge_1.8.... nogui.
```

**Comment by cuchaz** [comment]
I worked around the problem by putting the full path to the jar in my config. Thanks though.

**Comment by benediktschmitt** [comment]
So, fixed this in the *dev* branch. The changes will be available in version 4.
