### ISSUE TITLE
Cannot start a world

### ISSUE THREAD

**Issue by linluxiang** [benediktschmitt/emsm#50]
I cannot start a world based on server minecraft forge 1.8. I got this error "error: the world could not be started." and I didn't event see the execution of starting command.

I think maybe this is because the space in server name.

I suggest to use minecraft_forge_1.8 to replace "minecraft forge 1.8". The server can be installed in a fold er without the spaces in the name

**Comment by benediktschmitt** [comment]
It's working on my machine (debian). I used this configuration for testing:

*worlds.conf*:
```init
[forge 1.8 test]
server = minecraft forge 1.8
```

```Shell
$ minecraft -w "forge 1.8 test" worlds --start
```

Did you try to clean the *server/* directory?

**Comment by Foolson** [comment]
Well I got this

    stilkraft:
         error: the world could not be started.

in a clean install when I ran

    minecraft -W worlds --start

And I don't have spaces in the name. So this have to be something else.

worlds.conf
```
[DEFAULT]
stop_timeout = 10
stop_delay = 5 
stop_message = The server is going down.
    Hope to see you soon. 
     
[stilkraft]
server = vanilla 1.8
```

server.conf
```
[vanilla 1.8]
url = https://s3.amazonaws.com/Minecraft.Download/versions/1.8.3/minecraft_server.1.8.3.jar
start_command = java -Xmx6G -Xms6G -jar {server_exe} nogui
```

**Comment by benediktschmitt** [comment]
@Foolson thank you for the configuration, helped me to find the problem. @linluxiang you were right, it was a whitespace problem: When an own start command has been defined, the ``{server_exe}`` and ``{server_dir}`` placeholders have not been quoted.

However, there is now another problem: When extending the *server_dir* path, the EMSM will quote it wrong. So this will not work:
```
start_command = ... {server_dir}/minecraft_server.jar ...
```
I leave this issue open until this is fixed too.
