### ISSUE TITLE
/opt/minecraft/minecraft.py not being created.

### ISSUE THREAD

**Issue by Macrobiotic** [benediktschmitt/emsm#51]
I can't seem to create the minecraft.py file.

Whenever I run emsm.run(instance_dir="/opt/minecraft") in python, I get the following error:

Error in atexit._run_exitfuncs:
PermissionError: [Errno 13] Permission denied

All the other directories and files are created, but somehow minecraft.py isn't.

What am I doing wrong?

I'm running on CentOS 7

**Comment by benediktschmitt** [comment]
Are you able to create the ``/opt/minecraft/minecraft.py`` file as described in the docs and to execute it? Please make sure, that the whole directory is owned by the minecraft user: ``chown -R minecraft:minecraft /opt/minecraft``.

Is the log created? If yes, can you attach the traceback of the exception in the log files? This should be something like: 
```
Traceback (most recent call last):
  ......
  File "<pyshell#0>", line 1, in <module>
    raise PermissionError()
PermissionError
```
The traceback would help me a lot by finding the source of the error.

**Comment by Macrobiotic** [comment]
I deleted the /opt/minecraft directory along with all its contents, and ran the chmod command before attempting to run emsm.run(instance_dir="/opt/minecraft")

It didn't help.

I've tried to use traceback, but since I've not used python before, I'm not having much luck with the syntax.

The examples I have found online haven't worked, so I'm not sure where I'm going wrong.

**Comment by benediktschmitt** [comment]
The EMSM crates a log file in ``/opt/minecraft/logs/`` and logs the traceback there. The logs can become quite big, so you can start searching at the end. A new EMSM start is indicated by the log record "settings the EMSM [...] up". 

I'm currently installing centOS and trying to run the EMSM there.

Alternatively, you can try to start the EMSM without using the run method:
```
import emsm
app = emsm.core.application.Application(instance_dir="/opt/minecraft")
app.setup()
app.run()
app.finish()
```
This is also what ``run()`` does, but without catching the exceptions.

**Comment by benediktschmitt** [comment]
By the way: Are you using python3 (if yes, is there a yum package?)?

**Comment by Macrobiotic** [comment]
I had to compile python3 from source. There doesn't seem to be a yum package available for anything newer than a version around 2.7.

I looked at the log file you mentioned and I can't find any errors. Everything seems to complete, but there is no line where it attempts to create minecraft.py

I'll try starting EMSM without using run().

**Comment by Macrobiotic** [comment]
OK.. I found something odd.

The error only happens when I exit form python3.

All the commands you gave me run seemingly without error. The error happens after I complete the last command, and type; exit()

>>> app = emsm.core.application.Application(instance_dir="/opt/minecraft")
>>> app.setup()
>>> app.run()
>>> app.finish()
0
>>> exit()
Error in atexit._run_exitfuncs:
PermissionError: [Errno 13] Permission denied

**Comment by benediktschmitt** [comment]
Oh, sorry I think I undestood you wrong.

The *minecraft.py* file is not created automatically. You need to create it yourself in ``/opt/minecraft/``. After switching to ``/opt/minecraft/`` you should be able to run the EMSM by: ``python3 minecraft.py``.

**Comment by Macrobiotic** [comment]
OK.. I was getting quite confused.

How do I create minecraft.py ?

Do I just save an empty text file and call it minecraft.py, or is there more to it?

**Comment by benediktschmitt** [comment]
No, just create a new empty file with the content in the docs. That's all.

**Comment by Macrobiotic** [comment]
OK, I'll give that a try.

Many thanks.

**Comment by benediktschmitt** [comment]
I guess, this issue is solved. If not, please reopen it.

**Comment by Macrobiotic** [comment]
Once I have a chance to try properly, I will provide feedback.

Many thanks for the help so far.
