### ISSUE TITLE
GNU Screen options

### ISSUE THREAD

**Issue by xdillweedx** [benediktschmitt/emsm#52]
Hi, still lovin' EMSM.  Would it be possible to add 'screen' options?  For example, I want to increase the scrollback buffer from the default 100 lines to something larger, say 10,000 lines.  I think that when the server starts it would be nice read a .screenrc to get override the defaults.
Thanks!

**Comment by benediktschmitt** [comment]
Thank you :)

I added a new configuration option in the *main.conf* configuration file (see docs). I still need to test, if it works as expected.
I already uploaded the new version to PyPi. So you can directly download it from there.

**Comment by xdillweedx** [comment]
Right on.  Love the response time and again thank you! 

I'll give it a try and report back with any problems.
