### ISSUE TITLE
Custom java options per world

### ISSUE THREAD

**Issue by kayila** [benediktschmitt/emsm#57]
It would be really nice if we could pass custom java options on a per world basis. For example, i might want to run one world/server with 5GB of ram and another with 2GB. If my understanding is correct, those options can only be configured on a per-server basis.

Two ways I could think of doing this is either allow a world to override the start command or add a field that gets added into the start command (Maybe have like a `{worldopts}` field that gets filled in with whatever from the world config.

**Comment by benediktschmitt** [comment]
Hi,

I don't know, when I'll be able to implement these features. (The semester just started, so it may take a while until I have some time). The issue #58 and this one could both be handled introducing a new comment format or section for each world in the *ini* file. Something like:

```ini
[myworld]
stop_timeout = ...

[myworld::backup]
filter = ...
format = ...

[myworld::server]
start_command = ...
```

Then there is also issue #50, which should be fixed in the same release.

**Comment by benediktschmitt** [comment]
Each world has now its own configuration file and some options for the EMSM, server and plugins can be overridden for each world. 

*morph.world.conf*
```ini
[world]
stop_timeout = 10
stop_delay = 5
stop_message = The server is going down.
	Hope to see you soon.
server = vanilla 1.10

[plugin:backups]
max_storage_size = 10
archive_format = zip
exclude_paths = banned-ips.json
    mods

[plugin:initd]
enable = yes

[server:vanilla 1.10]
start_command = java -Xms512m -Xmx1G -jar {server_exe} nogui

[server:vanilla 1.9]
start_command = java -Xms1G -Xmx1G -jar {server_exe} nogui
```

Please take a look at change-log and documentation for further information.
