### ISSUE TITLE
Backup plugin exclude filter

### ISSUE THREAD

**Issue by kayila** [benediktschmitt/emsm#58]
It'd be useful if we could specify a filter to exclude from the backup plugin. For example I'd love to be able to exclude `mods/*` to reduce the size of my world backups on my forge server. Maybe this could/should be part of world configuration as well so it doesn't have to be passed on every call. (And maybe make a new backup flag `--create-full` which will backup everything ignoring the filter to backup the mods or whatever too.)

**Comment by benediktschmitt** [comment]
If you're still using the EMSM (I hope so), you can now specify *exclude_paths* in the configuration. These paths can be specified once for all worlds in the *main.conf* configuration file or for each world separate in the world's configuration file (*.world.conf*).

I will upload the new EMSM version to PyPi on the weekend.
