### ISSUE TITLE
Vanilla Version 1.11

### ISSUE THREAD

**Issue by wucop** [benediktschmitt/emsm#65]
I am currently trying to install EMSM on my new server. What I have done so far is that I have finished the installation tutorial. The next step would be to setup a world, but I have some problems doing so.

Following the tutorial I tried to add Vanilla 1.11 to the server.conf in order to get Vanilla 1.11 running (Vanilla 1.11 wasn't there ...). The settings are:

> [vanilla 1.11]
> url = https://s3.amazonaws.com/Minecraft.Download/versions/1.11.2/minecraft_server.1.11.2.jar
> start_command = java -Xmx6G -Xms6G -jar {server_exe} nogui

or only

> [vanilla 1.11]

After running the command

> minecraft -s "vanilla 1.11" server --update

a problem occurs:

> minecraft: error: argument -s/--server: invalid choice: 'vanilla 1.11' (choose from 'minecraft forge 1.10', 'vanilla 1.2', 'minecraft forge 1.8', 'vanilla 1.9', 'minecraft forge 1.7', 'vanilla 1.6', 'vanilla 1.8', 'vanilla 1.4', 'vanilla 1.10', 'spigot latest', 'minecraft forge 1.6', 'vanilla 1.3', 'bungeecord', 'vanilla 1.5', 'vanilla 1.7')

And the big question is what I have done wrong. The version of EMSM is 5.0.0 beta so it should be the latest version.

Also I am wondering about your world.conf within the tutorial, because you already refer to Vanilla 1.11

> [world]
> ...
> server = vanilla 1.11

so it must be possible to run Vanilla 1.11...

Thank you very much for your efforts and I really would be happy if you can help me.

Best regards,
Dennis

PS: Running on Ubuntu 16.04.1 with Python 3.5

**Comment by benediktschmitt** [comment]
Hi Dennis,

I forgot to upload the latest version to pypi. When you upgrade the Python package, the EMSM v5.0.2-beta should be installed (which contains the vanilla 1.11 server wrapper).

**Comment by wucop** [comment]
Thanks for the fast answer! 
Was able to update to v5.0.2-beta and vanilla 1.11 is now available :-)

Will configure the new world tomorrow and give a final feedback.

Thanks so far!

Best regards,
Dennis

**Comment by wucop** [comment]
It's working absolutly fine.
Thank you very much!
