### ISSUE TITLE
Libjaml error on Debian Jessie

### ISSUE THREAD

**Issue by SilkAndSlug** [benediktschmitt/emsm#66]
Installing as per [ReadTheDocs](http://emsm.readthedocs.io/en/latest/how_to/installation.html). Step #3 is:

    sudo pip3 install --pre emsm

Which produces this error:

    Running setup.py install for pyyaml
    checking if libyaml is compilable
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -c build/temp.linux-x86_64-3.4/check_libyaml.c -o build/temp.linux-x86_64-3.4/check_libyaml.o
    build/temp.linux-x86_64-3.4/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
     #include <yaml.h>
                      ^
    compilation terminated.

    libyaml is not found or a compiler error: forcing --without-libyaml
    (if libyaml is installed correctly, you may need to
     specify the option --include-dirs or uncomment and
     modify the parameter include_dirs in setup.cfg)

    Successfully installed emsm blinker filelock termcolor pyyaml
    Cleaning up...

No error message, but no user expects to see "compilation terminated".  ;-)

**Comment by SilkAndSlug** [comment]
I've completed installation as per [ReadTheDocs](http://emsm.readthedocs.io/en/latest/how_to/installation.html), and `minecraft emsm --version` returned `5.0.2-beta` -- so the installation presumably completed okay.

**Comment by benediktschmitt** [comment]
This is a problem with the *pyyaml* package, which we need to parse one type of server configuration (not sure, but I think it was the one from bungeecord or forge?).  As far as I know pyyaml falls back to a pure Python implementation in those cases that is a bit slower, but that's not a problem here.
