### ISSUE TITLE
Can't check-update on EMSM

### ISSUE THREAD

**Issue by SilkAndSlug** [benediktschmitt/emsm#67]
`minecraft emsm --check-update` fails with ValueError:

```
root@sas171:/opt/minecraft/conf# minecraft emsm --check-update
EMSM: Uncaught exception:
 > Exception: ValueError
 > Module     /usr/local/lib/python3.4/dist-packages/emsm/plugins/emsm.py
 > Message:   need more than 3 values to unpack
 > A full traceback can be found in the log file.
```

Log file ends:
```
[2017-02-01 21:54:23][ERROR   ][application              ] uncaught exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/emsm/__init__.py", line 42, in run
    app.run()
  File "/usr/local/lib/python3.4/dist-packages/emsm/core/application.py", line 347, in run
    self._plugins.run()
  File "/usr/local/lib/python3.4/dist-packages/emsm/core/plugins.py", line 426, in run
    plugin.run(args)
  File "/usr/local/lib/python3.4/dist-packages/emsm/plugins/emsm.py", line 260, in run
    self._action_check_update()
  File "/usr/local/lib/python3.4/dist-packages/emsm/plugins/emsm.py", line 242, in _action_check_update
    if updater.version_is_outdated():
  File "/usr/local/lib/python3.4/dist-packages/emsm/plugins/emsm.py", line 150, in version_is_outdated
    latest_version = self.latest_version()
  File "/usr/local/lib/python3.4/dist-packages/emsm/plugins/emsm.py", line 139, in latest_version
    latest_version = self._split_version(latest_version)
  File "/usr/local/lib/python3.4/dist-packages/emsm/plugins/emsm.py", line 105, in _split_version
    [major, minor, patch, phase] = re.split("[.-]", version)
ValueError: need more than 3 values to unpack
[2017-02-01 21:54:23][INFO    ][application              ] EMSM finished.
```

This is in version `5.0.2-beta`.

**Comment by suresttexas00** [comment]
Try changing that line 105 in emcm.py to `[major, minor, patch, phase] = re.split("[.-]", version.VERSION)`

Before you do that, you may want to try a print statement to find out the value of `version`.  My suspicion is that it is a module object (`emsm/core/version.py` imported by `emsm/core/application.py` in line 52).

the actual version might be the constant VERSION in that module.

**Comment by SilkAndSlug** [comment]
Changing L105 as per the above gives the following error:

    root@sas171:/opt/minecraft/conf# minecraft emsm --check-update
    EMSM: Uncaught exception:
     > Exception: AttributeError
     > Module     /usr/local/lib/python3.4/dist-packages/emsm/plugins/emsm.py
     > Message:   'str' object has no attribute 'VERSION'
     > A full traceback can be found in the log file.

**Comment by suresttexas00** [comment]
Did you get a print of what `version` actually is at run-time? (change version.VERSION back to just version and put a `print(version)` line somewhere just before the erroring line...)

we need to see what value/item re is trying to parse to see why it fails to deliver 4 items.

**Comment by SilkAndSlug** [comment]
`print(version)` returns `5.0.2b0`. I've traced that back, and that's the string being fetched from  `https://pypi.python.org/pypi?:action=doap&name=emsm`. That suggests, to me, that either someone's misnamed the package-as-uploaded, which is a bug on the upload(er), or the current version of EMSM has a broken self-updater.

**Comment by suresttexas00** [comment]
I agree.  That version should say `5.0.2.b0`, I believe.  That is why the re.split does not produce four items.

So it appears to be a problem with the uploader.

**Comment by benediktschmitt** [comment]
Sorry for the late answer. Since we use *pip* to install the *EMSM*, it is probably easier to remove the 
**--check-update** command and replace it with something like
```
pip3 list --outdated | grep emsm
```
I'll update the documentation in the next days.
