### ISSUE TITLE
Many "Unknown command" reports causing server to crash

### ISSUE THREAD

**Issue by I-question-this** [benediktschmitt/emsm#73]
I have a fresh installation of emsm, but am unable to get one of my servers to stay on. There are many reports of "Unknown command" before it closes.

[2017-06-02-4.log.txt](https://github.com/benediktschmitt/emsm/files/1049759/2017-06-02-4.log.txt) First sight of issue.
[latest.log.txt](https://github.com/benediktschmitt/emsm/files/1049760/latest.log.txt) What occurs when server is restarted.

**Comment by benediktschmitt** [comment]
It's hard to tell from the server logs what's going on. Perhaps you can find more information in the EMSM logs. It would be helpful if you can post the associated EMSM log section (starts and ends with a *----------*).
