### ISSUE TITLE
Unable to upgrade Forge 1.6 using EMSM 5.0.7b0

### ISSUE THREAD

**Issue by SilkAndSlug** [benediktschmitt/emsm#76]
As root, I ran this command `minecraft -s 'minecraft forge 1.6' server --update` and got this response:

    EMSM: Uncaught exception:
    > Exception: TypeError
    > Module     /usr/local/lib/python3.5/dist-packages/emsm/core/server.py
    > Message:   'str' object is not callable
    > A full traceback can be found in the log file.

[emsm.log](https://github.com/benediktschmitt/emsm/files/1670617/emsm.log)

Forge 1.7 worked.

**Comment by benediktschmitt** [comment]
The URL for 1.6 did not exist anymore and it should work now (although I did not test).

**Comment by SilkAndSlug** [comment]
Confirmed as working in v5.0.9b. I'm happy for you to close this issue.

**Comment by SilkAndSlug** [comment]
Confirmed as working in v5.0.9b. I'm happy for you to close this issue.

**Comment by benediktschmitt** [comment]
:)
