### ISSUE TITLE
Version-number confusion

### ISSUE THREAD

**Issue by SilkAndSlug** [benediktschmitt/emsm#77]
The GitHub repo has [tags for four releases](https://github.com/benediktschmitt/emsm/releases), ending v4.0.16b. The [README lists two releases](https://github.com/benediktschmitt/emsm), ending v2.0.1b. [ReadTheDocs](http://emsm.readthedocs.io/en/latest/changelog.html) ends with v5.0.8b -- but doesn't have v5.0.7b. Pip3 offers v5.0.9b.

Pretty low priority, but I thought I might as well mention it.  :-)

**Comment by benediktschmitt** [comment]
The version releases are mostly minor bug fixes, which would result in one tag <-> one commit.
For consistency, I remove the tags on GitHub ;), but I'll leave the links to the PyPi history here:
* https://pypi.org/project/emsm/#history
* https://pypi.python.org/simple/emsm/
