### ISSUE TITLE
Specific spigot version?

### ISSUE THREAD

**Issue by KronK0321** [benediktschmitt/emsm#80]
I'm running multiple worlds with different spigot versions due to plugin requirements. Is there a way I can use the server wrappers for spigot to accomplish this? Currently, the only working spigot is [spigot latest] which isn't what I'm looking for.

Thanks!

**Comment by benediktschmitt** [comment]
I added the other spigot versions, starting with 1.8, in 9247202955ed2d7b80e6478547e9daf9ac35d117. Please let me know, if something does not work.

**Comment by KronK0321** [comment]
Awesome, thank you!
