### ISSUE TITLE
Plugin install not working (error paths has no plugins_dir argument)

### ISSUE THREAD

**Issue by BannukDE** [benediktschmitt/emsm#81]
https://github.com/benediktschmitt/emsm/blob/9247202955ed2d7b80e6478547e9daf9ac35d117/emsm/plugins/plugins.py#L246
> Change request:
> `self._app.paths().plugins(), self._name +   ".py"`

https://github.com/benediktschmitt/emsm/blob/9247202955ed2d7b80e6478547e9daf9ac35d117/emsm/plugins/plugins.py#L260
> Change request:
> `self._app.paths().plugins(), self._name + ".py"`

https://github.com/benediktschmitt/emsm/blob/9247202955ed2d7b80e6478547e9daf9ac35d117/emsm/plugins/plugins.py#L278
> Change request:
> `emsm_data_dir = self._app.paths().plugin_data(self._name)`

https://github.com/benediktschmitt/emsm/blob/9247202955ed2d7b80e6478547e9daf9ac35d117/emsm/plugins/plugins.py#L311
> Change request:
> `emsm_data_dir = self._app.paths().plugin_data(self._name)`

**Comment by benediktschmitt** [comment]
Thank you!
