### ISSUE TITLE
Transfer of maintenance

### ISSUE THREAD

**Issue by benediktschmitt** [benediktschmitt/emsm#93]
(This issue continues the discussion in #84)

Hi all!
As you may have guessed, I don't play minecraft that often anymore. I agree with @SilkAndSlug and @BrendanMcCallum that it is probably better if the current maintainer is using the EMSM. 

I think the easiest way is to add new maintainers/collaborators to this repository and the PyPi package, although I can see myself turning this repository into an archive and linking to a fork, if the fork is proper maintained (yeah, I see the irony and only time will tell which fork is the "best" choice). Also, I'd prefer the first method in order to keep URLs intact and avoid "competing" forks.

@SilkAndSlug, you've been active here for a long time. I'd grant you access to the maintenance features of the EMSM if you are still willed to handle the admin stuff and PyPi uploads.

**Comment by SilkAndSlug** [comment]
@benediktschmitt I'm happy to handle the admin stuff & the PyPi uploads. I've not used PyPi before, so I'm happy to accept help there.

**Comment by SilkAndSlug** [comment]
I've created an organisation called emsm-org

**Comment by SilkAndSlug** [comment]
I've invited @benediktschmitt as Owner and @BrendanMcCallum as Member. Benedikt -- I've not done this before, but believe you can transfer ownership of your EMSM repo to the Org. I hope(!) that will keep the history, issues, forks, etc intact.

**Comment by benediktschmitt** [comment]
Thanks for taking over! I've invited you both to this repository (The link to the org expired). When you have created a PyPi account (pypi.org), then I can give you permission to maintain the package there as well (uploads, ...), I only need your username. I use twine https://twine.readthedocs.io/en/latest/ to upload the packages. You may want to use the *testpypi* server first to make sure, everything works. Let me know if something goes wrong. 

(I'll check if I can add a Webhook, so that you can upload the release to PyPi from Github.)

**Comment by SilkAndSlug** [comment]
I've added a webhook for linting, triggered by push, and a webhook to build-and-publish to test.PyPi, triggered by release. The publish task is still bedding in, but that shouldn't be a problem.

**Comment by SilkAndSlug** [comment]
Please will @benediktschmitt contact me off-list (e.g. via Twitter ; same username) with login details for PyPi? I can also see signs of Tox, Nose, and a code-coverage tool. Please will you send me those tests & configs, and anything else I might need?

**Comment by SilkAndSlug** [comment]
_bump_ @benediktschmitt

**Comment by SilkAndSlug** [comment]
I no longer think I'm the right person to be maintaining this code or repo, so I hereby resign. I suggest someone else volunteer.
