### ISSUE TITLE
Cloudron apps

### ISSUE THREAD

**Issue by Skywrath-Mage** [benediktschmitt/emsm#94]
Hello, 

i work with cloudron as a control panel for docker and the have "Minecraft Apps" but thery are intended as flexible as your script can be. 

So if you help me we can build a dockerized version compatible with cloudron of your script.

**Comment by SilkAndSlug** [comment]
We have no intention of supporting Cloudron at the moment. I'm closing this issue for now, but am happy to re-open if someone wants to help with this.
